
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3521/tcarsenalmarketing?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false
    username: root
    password: 123456
    
    

#pagehelper分页插件配置
pagehelper:
  helperDialect: postgresql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
